---
- name: Install unzip
  yum: name=unzip state=present

- name: Get static content
  shell: ls -l /var/www/html
  register: content

- debug: var=content

- name: Undeploy previous version of static content
  file: path=/var/www/html/{{item}} state=absent
  with_items: "{{content.stdout_lines}}"

- name: Deploy static content
  unarchive: src={{ }} dest=/var/www/html